baseURL: "https://incelwikibrasil.github.io/"
title: Incel Wiki Brasil
theme: wiki-theme

languageCode: en
defaultContentLanguage: en
timeZone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

params:
  date_format: "15h04m UTCMST de 02 de January de 2006" # https://gohugohq.com/howto/hugo-dateformat/
  site_subtitle: "a tradução brasileira da [Incel Wiki](https://incels.wiki/w/Main_Page)."
  repo_link: https://github.com/incelwikibrasil/incelwikibrasil.github.io
  remove_from_random: # Random will use all .Site.RegularPages
    url: 
  discord_invite: teste

enableGitInfo: true

taxonomies:
  categoria: categorias

frontmatter:
  date:
  - :default
  lastmod:
  - :fileModTime

markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
    parser:
      autoHeadingIDType: github-ascii
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2

module:
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-seo
    - path: "github.com/davidsneighbour/hugo-opensearch"
      disable: false
      ignoreConfig: false
      ignoreImports: false
    - path: "github.com/davidsneighbour/github.com/davidsneighbour/hugo-pwa"
      disable: false
      ignoreConfig: false
      ignoreImports: false
    - path: "github.com/davidsneighbour/hugo-robots"
    - path: "github.com/davidsneighbour/github.com/davidsneighbour/hugo-security"
      disable: false
      ignoreConfig: false
      ignoreImports: false
    - path: "github.com/davidsneighbour/hugo-sitemap"
