baseURL: "https://incelwikibrasil.github.io/"
title: Incel Wiki Brasil
theme: wiki-theme

languageCode: en
defaultContentLanguage: en
timeZone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

params:
  date_format: "15h04m UTCMST de 02 de January de 2006" # https://gohugohq.com/howto/hugo-dateformat/
  site_subtitle: "a tradução da [Incel Wiki](https://incels.wiki/w/Main_Page)."
  repo_link: https://github.com/incelwikibrasil/incelwikibrasil.github.io
  remove_from_random: # Random will use all .Site.RegularPages
    url: /sobre/

taxonomies:
  categoria: categorias

###############################
enableGitInfo: true

markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
    parser:
      attribute:
        link: true
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2
