baseURL: "https://incelwikibrasil.netlify.app/"
title: Incel Wiki Brasil
theme: wiki-theme

languageCode: pt
defaultContentLanguage: pt
timeZone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

params:
  description: Incel é o termo para a circunstância de vida adversa de completa ausência de relacionamentos amorosos ou afetivos apesar da vontade de tê-los.
  date_format: "15h04m UTCMST de 02 de January de 2006" # https://gohugohq.com/howto/hugo-dateformat/
  site_subtitle: "a tradução brasileira da [Incel Wiki](https://incels.wiki/w/Main_Page)."
  repo_link: https://github.com/aUnuser/Incel-Wiki-Brasil
  remove_from_random: # Random will use all .Site.RegularPages
    url: 
  discordInvite: https://discord.gg/KfvZsvV3qg
  
  tnd_seo:
    # overrides .Site.Title
    site_name: Incel Wiki Brasil
    # Used for articles without images
    default_image: "/main_thumb.png"
    # if true will use the SEO data object to output an json+ld script tag.
    jsonld: true
    disable_title_tag: false
    # if true module will handle follow/nofollow tags for pages depending on environment and Front Matter setting.
    enable_follow: false

  dnb:
    opensearch:
      description: Busque na Incel Wiki Brasil # Search description, MUST be shorter than 1024 characters and MUST NOT contain markup. Default is Search on {{ site.Title }}
      query_url: # Url to the search result page. Replace the location of the searchterm with {searchterms}. Default is search/?q={searchTerms}. This variable will be prefixed with the baseUrl
      search_form: # Url to the search form. Default is search/. This variable will be prefixed with the baseUrl and is used by Firefox to link to the page with the search form.
      enable_autoupdate: false # Enable auto update for the search update. Default is true. At this time, addons.mozilla.org (AMO) doesn't support automatic updating of OpenSearch plugins. If you want to put your search plugin on AMO, then set this parameter to false.
    security:
      txt:
        contact: "https://twitter.com/incelwikibrasil" # Required
        languages: "pt"

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableGitInfo: true

taxonomies:
  categoria: categorias

frontmatter:
  lastmod: 
    - lastmod
    - :fileModTime

markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
    parser:
      autoHeadingIDType: github-ascii
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2

module:
  imports:
    - path: "github.com/theNewDynamic/hugo-module-tnd-seo"
    - path: "github.com/davidsneighbour/hugo-robots"
    - path: "github.com/davidsneighbour/hugo-security"
      disable: false
      ignoreConfig: false
      ignoreImports: false
    - path: "github.com/davidsneighbour/hugo-sitemap"

enableRobotsTXT: true
